### ISSUE TITLE
Load crashes after removing some trees

### ISSUE THREAD

**Issue by ATJonzie** [LiftPizzas/BuggyExchange-RRO#1]
I used the newest version and when I removed some trees then tried loading the world it crashed.

**Comment by ATJonzie** [comment]
[UE4CC-Windows-DC21D73446CB4277E9ECEA854F6591F9_0001 - Copy.zip](https://github.com/LiftPizzas/BuggyExchange-RRO/files/10150259/UE4CC-Windows-DC21D73446CB4277E9ECEA854F6591F9_0001.-.Copy.zip)

**Comment by ATJonzie** [comment]
that is my crash report

**Comment by LiftPizzas** [comment]
Can you attach the save? (UE4 crash report doesn't tell me anything.)
How many trees did you remove, just a few, a whole lot, all of them?
Are you able to load up the save in ROSE?

**Comment by ATJonzie** [comment]
[slot4.zip](https://github.com/LiftPizzas/BuggyExchange-RRO/files/10150471/slot4.zip)

**Comment by ATJonzie** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/110944913/205545341-63297dd5-8a61-4f45-957c-c1d51d635bf5.png)

**Comment by ATJonzie** [comment]
thats what I get through ROSE

**Comment by LiftPizzas** [comment]
Ok, looking at the save, there are a couple of cars that have names and numbers that the editor can't parse. (I haven't decoded their method for these so there's no way for me to make it fix or deal with them when loading in a save.)

This causes the editor to corrupt the car names/numbers when writing an output file. You should be able to fix it by loading up a save in ROSE and emptying out the names/numbers (or just make them all "1" or whatever, to overwrite what's there.) and then use the output of that in BuggyExchange to do your tree trimming.

When you buy new cars (the new engines especially, it seems) I recommend giving them a short name and number so that it writes them into the save file. I know it's a workaround but editing saves is already a workaround. ;)

I'll need to add this info to the readme/instructions/whatever so people don't get caught up by it.

**Comment by ATJonzie** [comment]
so, I should probably delete all locomotives and cars and repurchase them?

**Comment by ATJonzie** [comment]
The problem is that I cannot access the save through ROSE, I get the error above

**Comment by LiftPizzas** [comment]
You can't go back to an earlier save? Did you overwrite your original with the editor? (Always make a copy to edit, that's standard with all save editors for all games for all time.) If you made a backup the only work you would lose is whatever you did in buggy exchange (deleting a few trees) which can be redone after fixing the pre-edited save.

**Comment by ATJonzie** [comment]
luckily it was a fairly new save, only a route to the sawmill and logging camp. But I did not follow correct backup safety. Thanks for the help anyways.
